#配置 Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
  instance:
    preferIpAddress: true
server:
  port: 2000  #服务端口号
spring:
  application:
    name: public-client #服务名称--调用的时候根据名称来调用该服务的方法